plugins {
    id 'java'
}

group = 'com.sprint.mission'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2' // Jackson Databind 라이브러리 추가
}

test {
    useJUnitPlatform()
}